# Dockerfile for copying local `./dist` into the docker image.
#
#   The goal of this dockerfile is to efficiently achieve
#   multi-architectural build.
#
#   The app should be built in the physical machine using `npm run build`
#   before applying this dockerfile.
#
FROM node:20.7-alpine

RUN npm i -g sirv-cli

WORKDIR /app

COPY ./dist /app
COPY ./docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
ENV HOST=0.0.0.0 PORT=3000
CMD ["sirv", "--etag", "--single"]
EXPOSE 3000
