import React from "react";
import { Form, Label, TextInput, Button } from "@patternfly/react-core";
import { PluginParameter } from "@fnndsc/chrisapi";
import SimpleDropdown from "./SimpleDropdown";
import { Plugin } from "@fnndsc/chrisapi";

interface GuidedConfigState {
  isOpen: boolean;
  componentList: any[];
  value: string;
  paramName: string;
}

interface GuidedConfigProps {
  params: PluginParameter[];
  inputChange(id: number, paramName: string, value: string): void;
  userInput: {
    [key: number]: {
      [key: string]: string;
    };
  };
  plugin?: Plugin;
  deleteInput(input: string): void;
}

class GuidedConfig extends React.Component<
  GuidedConfigProps,
  GuidedConfigState
> {
  constructor(props: GuidedConfigProps) {
    super(props);
    this.state = {
      isOpen: false,
      componentList: [],
      value: "",
      paramName: ""
    };
  }

  handleInputChange = (
    value: string,
    event: React.FormEvent<HTMLInputElement>
  ) => {
    const { inputChange } = this.props;
    event.persist();
    const target = event.target as HTMLInputElement;
    const name = target.name;

    this.setState(
      {
        value,
        paramName: name
      },
      () => {
        //Required params have a default id of 0
        const id = 0;
        inputChange(id, this.state.paramName, this.state.value);
      }
    );
  };

  deleteComponent = (id: number) => {
    const { componentList } = this.state;

    let component = componentList.filter((component, index) => {
      return index !== id;
    });

    this.setState(
      {
        componentList: component
      },
      () => {
        console.log(this.state.componentList);
      }
    );
  };

  renderRequiredParams = () => {
    const { params } = this.props;

    let count = 1;
    return params.map(param => {
      if (param.data.optional === false) {
        count += 1;
        return (
          <Form className="required-params" key={count}>
            <Label className="required-label">{`${param.data.flag}:`}</Label>
            <TextInput
              aria-label="required-param"
              spellCheck={false}
              onChange={this.handleInputChange}
              name={param.data.name}
              className="required-param"
            />
          </Form>
        );
      }
    });
  };

  addParam = () => {
    const { componentList } = this.state;
    const { params, inputChange, deleteInput } = this.props;

    if (componentList.length < params.length) {
      const key = componentList.length;

      this.setState({
        componentList: [
          ...componentList,
          <SimpleDropdown
            key={key}
            params={params}
            handleChange={inputChange}
            id={key}
            deleteComponent={this.deleteComponent}
            deleteInput={deleteInput}
          />
        ]
      });
    } else {
      console.log("You cannot add any more input Change parameters");
    }
  };

  renderDropdowns = () => {
    const { componentList } = this.state;
    return componentList.map(component => component);
  };

  render() {
    const { userInput, plugin } = this.props;

    let generatedCommand = plugin && `${plugin.data.name}: `;

    for (let object in userInput) {
      const flag = Object.keys(userInput[object])[0];
      const value = userInput[object][flag];
      generatedCommand += ` --${flag} ${value}`;
    }

    return (
      <>
        <Button onClick={this.addParam} variant="primary">
          Add Configuration options
        </Button>

        <div className="config-container">
          <div className="generated-config">
            {this.renderRequiredParams()}
            {this.renderDropdowns()}
          </div>

          <div className="autogenerated-config">
            <Label className="autogenerated-label">Generated Command:</Label>
            <TextInput
              className="autogenerated-text"
              type="text"
              aria-label="autogenerated-config"
              value={generatedCommand}
            />
          </div>
        </div>
      </>
    );
  }
}

export default GuidedConfig;
