import React from "react";
import { Form, Label, TextInput, Button } from "@patternfly/react-core";
import { PluginParameter } from "@fnndsc/chrisapi";
import SimpleDropdown from "./SimpleDropdown";
import { Plugin } from "@fnndsc/chrisapi";

interface GuidedConfigState {
  isOpen: boolean;
  componentList: any[];
  value: string;
  paramName: string;
}

interface GuidedConfigProps {
  params: PluginParameter[];
  inputChange(flag: string, value: string): void;
  userInput: {
    [key: string]: string;
  };
  plugin?: Plugin;
}

class GuidedConfig extends React.Component<
  GuidedConfigProps,
  GuidedConfigState
> {
  private autoRef: any;
  constructor(props: GuidedConfigProps) {
    super(props);
    this.state = {
      isOpen: false,
      componentList: [],
      value: "",
      paramName: ""
    };
    this.autoRef = React.createRef();
  }

  handleInputChange = (
    value: string,
    event: React.FormEvent<HTMLInputElement>
  ) => {
    const { inputChange } = this.props;
    event.persist();
    const target = event.target as HTMLInputElement;
    const name = target.name;
    console.log(name);

    this.setState(
      {
        value,
        paramName: name
      },
      () => {
        console.log(this.state.value, this.state.paramName);
        inputChange(this.state.paramName, this.state.value);
      }
    );
  };

  deleteComponent = (id: number) => {
    const { componentList } = this.state;

    let component = componentList.filter((component, index) => {
      return index !== id;
    });
    console.log(component);
    this.setState({
      componentList: component
    });
  };

  renderRequiredParams = () => {
    const { params } = this.props;

    return params.map(param => {
      if (param.data.optional === false) {
        return (
          <Form className="required-params" key={param.data.id}>
            <Label className="required-label">{`${param.data.flag}:`}</Label>
            <TextInput
              aria-label="required-param"
              spellCheck={false}
              onChange={this.handleInputChange}
              name={param.data.name}
            />
          </Form>
        );
      }
    });
  };

  addParam = () => {
    const { componentList } = this.state;
    const { params, inputChange } = this.props;

    console.log("ComponentList", this.state.componentList);

    if (componentList.length < params.length) {
      const key = componentList.length;

      this.setState({
        componentList: [
          ...componentList,
          <SimpleDropdown
            key={key}
            params={params}
            handleChange={inputChange}
            id={key}
            deleteComponent={this.deleteComponent}
          />
        ]
      });
    } else {
      console.log(
        "You cannot add any more inputChange={inputChange}e parameters"
      );
    }
  };

  renderDropdowns = () => {
    const { componentList } = this.state;
    return componentList.map(component => component);
  };

  render() {
    const { userInput, plugin } = this.props;

    let generatedCommand = plugin && `${plugin.data.name}: `;
    for (let i in userInput) {
      generatedCommand += ` --${i} ${userInput[i]}`;
    }

    return (
      <>
        <Button css="test" onClick={this.addParam} variant="primary">
          Add Configuration options
        </Button>

        <div className="config-container">
          <div className="generated-config">
            {this.renderRequiredParams()}
            {this.renderDropdowns()}
          </div>

          <div className="autogenerated-config">
            <Label className="autogenerated-label">Generated Command:</Label>
            <TextInput
              ref={this.autoRef}
              className="autogenerated-text"
              type="text"
              aria-label="autogenerated-config"
              placeholder={`${generatedCommand}`}
            />
          </div>
        </div>
      </>
    );
  }
}

export default GuidedConfig;
