name: ci

on:
  push:
    branches: [ master ]
    tags: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get info
        id: info
        run: |
          version="$(npm run -s print-version | tr '+' '-')"
          echo "Version: $version"
          echo "::set-output name=version_string::$version"

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        id: dockerhub_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: |
            docker.io/fnndsc/chris_ui:latest
            docker.io/fnndsc/chris_ui:${{ steps.info.outputs.version_string }}
            ghcr.io/fnndsc/chris_ui:latest
            ghcr.io/fnndsc/chris_ui:${{ steps.info.outputs.version_string }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: ChRIS user interface
          readme-filepath: ./README.md
          repository: fnndsc/chris_ui
